### ISSUE TITLE
Uncaught exception 'Exception' with message 'Warning: Invalid argument supplied for foreach() in /vendor/mirasvit/module-profiler/src/Profiler/Block/Tab/Sql.php on line 49'

### ISSUE THREAD

**Issue by cerebrumgit** [mirasvit/module-profiler#1]
Hello Good afternoon my friend

I installed your module and the following error is displayed as image

http://pasteboard.co/1evLeTJ1.png

Fatal error: Uncaught exception 'Exception' with message 'Warning: Invalid argument supplied for foreach() in /home/ubuntu/public_html/magento-2.0.0-dev17/vendor/mirasvit/module-profiler/src/Profiler/Block/Tab/Sql.php on line 49' in /home/ubuntu/public_html/magento-2.0.0-dev17/vendor/magento/framework/App/ErrorHandler.php:61 Stack trace: #0 /home/ubuntu/public_html/magento-2.0.0-dev17/vendor/mirasvit/module-profiler/src/Profiler/Block/Tab/Sql.php(49): Magento\Framework\App\ErrorHandler->handler(2, 'Invalid argumen...', '/home/ubuntu/pu...', 49, Array) #1 /home/ubuntu/public_html/magento-2.0.0-dev17/vendor/mirasvit/module-profiler/src/Profiler/view/base/templates/tab/sql.phtml(6): Mirasvit\Profiler\Block\Tab\Sql->getSlowQueries() #2 /home/ubuntu/public_html/magento-2.0.0-dev17/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/ubuntu/pu...') #3 /home/ubuntu/public_html/magento-2.0.0-dev17/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object( in /home/ubuntu/public_html/magento-2.0.0-dev17/vendor/magento/framework/App/ErrorHandler.php on line 61

**Comment by adrok** [comment]
Fixed.
For update module, run this command: composer update mirasvit/module-profiler
For enable profiler: bin/magento mirasvit:profiler:enable
