### ISSUE TITLE
Area code "empty" does not exist

### ISSUE THREAD

**Issue by sajidPatel** [mirasvit/module-profiler#10]
I have made the following changes to the enble command:

file: ../magento2ce/vendor/mirasvit/module-profiler/src/Profiler/Console/Command/EnableCommand.php

line 42: $this->appState->setAreaCode(\Magento\Framework\App\Area::AREA_FRONTEND);

Running: Magento ver. 2.2.0-dev

**Comment by Tantuss** [comment]
This makes it impossible to use in case you have Magento 2.1.7.

I get an error on the command line:
[Magento\Framework\Exception\LocalizedException]
  Area code is already set

After commenting out this code:
$this->appState->setAreaCode('empty');

The issue did go away.

So maybe to replace it to something like this:
if(empty($this->appState->getAreaCode()))
            $this->appState->setAreaCode('empty');
