### ISSUE TITLE
DB Query Caching?

### ISSUE THREAD

**Issue by jigneshthummar** [mirasvit/module-profiler#16]
what i observed on your demo is when i load any url very first time it come up with many queries (81) in following example but for second onwards requests it just make 4 DB calls how is this possible? 

![image](https://user-images.githubusercontent.com/1007936/28898987-b544e13a-77b6-11e7-95f3-16fdce6e2df6.png)

**Comment by adrok** [comment]
First view - without cache. Then magento load page from full page cache.
