### ISSUE TITLE
Can't see ajax calls

### ISSUE THREAD

**Issue by HOSTED-POWER** [mirasvit/module-profiler#17]
Hi,

Is there a way to also catch the ajax requests? They are handled on a "different" page and I think they're not shown.

In the past we used aoeprofiler, there you could easily see what happened since all was nicely stored in database and you could look into each request afterwards.

Might be a good idea to do something similar unless I'm missing something? :)

**Comment by adrok** [comment]
Hi,

I have changed the logic. Extension save all profiles to files (var/profiles) and then you can open profile for any request (regular, ajax or even CLI run)

http://profiler.m2.mirasvit.com/profiler/profile/index/
