### ISSUE TITLE
Magento 2.2 - PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Yaml\Dumper' not found in vendor/mirasvit/module-profiler/src/Profiler/Model/Storage.php:48

### ISSUE THREAD

**Issue by Tantuss** [mirasvit/module-profiler#22]
After the upgrade to Magento 2.2 the follow error is generated when the extension is enabled:

PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Yaml\Dumper' not found in vendor/mirasvit/module-profiler/src/Profiler/Model/Storage.php:48
Stack trace:
#0 vendor/mirasvit/module-profiler/src/Profiler/Model/Driver/Output/Html.php(39): Mirasvit\Profiler\Model\Storage->dump()
#1 vendor/magento/framework/Profiler/Driver/Standard.php(195): Mirasvit\Profiler\Model\Driver\Output\Html->display(Object(Magento\Framework\Profiler\Driver\Standard\Stat))
#2 [internal function]: Magento\Framework\Profiler\Driver\Standard->display()
#3 {main}
  thrown in vendor/mirasvit/module-profiler/src/Profiler/Model/Storage.php on line 48

**Comment by kabadabra** [comment]
run ```composer require symfony/yaml```

**Comment by angelflo** [comment]
Hi,
Same problem here with last magento 2.2.1 installed.
when I tried to run composer require symfony/yaml, I received error 

composer require symfony/yaml
Using version ^3.4 for symfony/yaml
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove magento/product-community-edition 2.2.1
    - Conclusion: don't install magento/product-community-edition 2.2.1
    - Installation request for magento/product-community-edition 2.2.1 -> satisfiable by magento/product-community-edition[2.2.1].
    - Conclusion: don't install symfony/yaml v3.4.1
    - magento/product-community-edition 2.2.1 requires symfony/console ~2.3, !=2.7.0 -> satisfiable by symfony/console[v2.8.32, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.0].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.1].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.10].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.11].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.12].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.13].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.14].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.15].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.16].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.17].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.18].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.19].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.2].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.20].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.21].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.22].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.23].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.24].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.25].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.26].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.27].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.28].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.29].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.3].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.30].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.31].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.32].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.33].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.34].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.35].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.36].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.37].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.38].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.39].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.4].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.40].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.41].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.42].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.5].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.6].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.7].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.8].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.3.9].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.4.0].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.4.1].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.4.10].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.4.2].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.4.3].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.4.4].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.4.5].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.4.6].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.4.7].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.4.8].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.4.9].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.5.0].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.5.1].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.5.10].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.5.11].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.5.12].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.5.2].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.5.3].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.5.4].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.5.5].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.5.6].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.5.7].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.5.8].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.5.9].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.6.0].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.6.1].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.6.10].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.6.11].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.6.12].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.6.13].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.6.2].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.6.3].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.6.4].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.6.5].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.6.6].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.6.7].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.6.8].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.6.9].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.1].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.10].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.11].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.12].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.13].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.14].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.15].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.16].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.17].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.18].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.19].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.2].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.20].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.21].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.22].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.23].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.24].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.25].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.26].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.27].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.28].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.29].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.3].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.30].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.31].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.32].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.33].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.34].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.35].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.36].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.37].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.38].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.39].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.4].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.5].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.6].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.7].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.8].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.9].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.0].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.1].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.10].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.11].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.12].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.13].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.14].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.15].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.16].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.17].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.18].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.19].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.2].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.20].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.21].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.22].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.23].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.24].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.25].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.26].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.27].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.28].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.29].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.3].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.30].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.31].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.32].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.4].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.5].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.6].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.7].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.8].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.9].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.32].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.32].
    - Installation request for symfony/yaml ^3.4 -> satisfiable by symfony/yaml[v3.4.0, v3.4.1].
Installation failed, reverting ./composer.json to its original content.

**Comment by yco85** [comment]
Hi,
I had the same problem two days ago... No way... I had to install newly Magento 2 and instal the Mirasvit module as first module...

**Comment by adrok** [comment]
The temporary fix is install symfony/yaml from dev branch and then our module:

composer require symfony/yaml:dev-issue-814
composer require mirasvit/module-profiler

In next release we'll add own library to use yaml.

**Comment by mrthao** [comment]
I installed Mage ce2.1, then installed the Mirasvit module as first module, after I  run " php -f bin/magento mirasvit:profiler:enable", I got error "PHP Fatal error: Uncaught Error: Class 'Symfony\Component\Yaml\Dumper' not found..."
Then I run "composer require symfony/yaml:dev-issue-814" but still get error

**Comment by ityetti** [comment]
@adrok You have a small mistake.
composer require symfony/yaml:dev-issue-814**5** - You probably forgot 5, because the branch 814 is not in this repository https://github.com/symfony/yaml

@mrthao Please check my comment.

**Comment by srlesrle** [comment]
after installing:
composer require symfony/yaml:dev-issue-8145
composer require mirasvit/module-profiler

it still gives me next error:
`12345s-MBP:magento2 a12345$ bin/magento dev:urn-catalog:generate .idea/misc.xml
PHP Fatal error:  Uncaught Error: Class 'Magentto\Framework\Component\ComponentRegistrar' not found in /Users/a12345/panel/magento/magento2.2/magento2/app/code/Mastering/SampleModule/registration.php:2
Stack trace:
#0 /Users/a12345/panel/magento/magento2.2/magento2/app/etc/NonComposerComponentRegistration.php(20): include()
#1 /Users/a12345/panel/magento/magento2.2/magento2/vendor/composer/autoload_real.php(70): require('/Users/a12345/p...')
#2 /Users/a12345/panel/magento/magento2.2/magento2/vendor/composer/autoload_real.php(60): composerRequire11d5400b9c0297ac88949bc52e76ff87('b4cf39431a4b949...', '/Users/a12345/p...')
#3 /Users/a12345/panel/magento/magento2.2/magento2/vendor/autoload.php(7): ComposerAutoloaderInit11d5400b9c0297ac88949bc52e76ff87::getLoader()
#4 /Users/a12345/panel/magento/magento2.2/magento2/app/autoload.php(30): include('/Users/a12345/p...')
#5 /Users/a12345/panel/magento/magento2.2/magento2/app/bootstrap.php(30): require_once('/Users/a12345/p...')
#6 /Users/a12345/panel/magento/magento2.2/magento2/bin/mage in /Users/a12345/panel/magento/magento2.2/magento2/app/code/Mastering/SampleModule/registration.php on line 2

Fatal error: Uncaught Error: Class 'Magentto\Framework\Component\ComponentRegistrar' not found in /Users/a12345/panel/magento/magento2.2/magento2/app/code/Mastering/SampleModule/registration.php:2
Stack trace:
#0 /Users/a12345/panel/magento/magento2.2/magento2/app/etc/NonComposerComponentRegistration.php(20): include()
#1 /Users/a12345/panel/magento/magento2.2/magento2/vendor/composer/autoload_real.php(70): require('/Users/a12345/p...')
#2 /Users/a12345/panel/magento/magento2.2/magento2/vendor/composer/autoload_real.php(60): composerRequire11d5400b9c0297ac88949bc52e76ff87('b4cf39431a4b949...', '/Users/a12345/p...')
#3 /Users/a12345/panel/magento/magento2.2/magento2/vendor/autoload.php(7): ComposerAutoloaderInit11d5400b9c0297ac88949bc52e76ff87::getLoader()
#4 /Users/a12345/panel/magento/magento2.2/magento2/app/autoload.php(30): include('/Users/a12345/p...')
#5 /Users/a12345/panel/magento/magento2.2/magento2/app/bootstrap.php(30): require_once('/Users/a12345/p...')
#6 /Users/a12345/panel/magento/magento2.2/magento2/bin/mage in /Users/a12345/panel/magento/magento2.2/magento2/app/code/Mastering/SampleModule/registration.php on line 2
PHP Fatal error:  Uncaught RuntimeException: ObjectManager isn't initialized in /Users/a12345/panel/magento/magento2.2/magento2/vendor/magento/framework/App/ObjectManager.php:35
Stack trace:
#0 /Users/a12345/panel/magento/magento2.2/magento2/vendor/mirasvit/module-profiler/src/Profiler/Model/Driver/Output/Html.php(17): Magento\Framework\App\ObjectManager::getInstance()
#1 /Users/a12345/panel/magento/magento2.2/magento2/vendor/magento/framework/Profiler/Driver/Standard.php(195): Mirasvit\Profiler\Model\Driver\Output\Html->display(Object(Magento\Framework\Profiler\Driver\Standard\Stat))
#2 [internal function]: Magento\Framework\Profiler\Driver\Standard->display()
#3 {main}
  thrown in /Users/a12345/panel/magento/magento2.2/magento2/vendor/magento/framework/App/ObjectManager.php on line 35

Fatal error: Uncaught RuntimeException: ObjectManager isn't initialized in /Users/a12345/panel/magento/magento2.2/magento2/vendor/magento/framework/App/ObjectManager.php:35
Stack trace:
#0 /Users/a12345/panel/magento/magento2.2/magento2/vendor/mirasvit/module-profiler/src/Profiler/Model/Driver/Output/Html.php(17): Magento\Framework\App\ObjectManager::getInstance()
#1 /Users/a12345/panel/magento/magento2.2/magento2/vendor/magento/framework/Profiler/Driver/Standard.php(195): Mirasvit\Profiler\Model\Driver\Output\Html->display(Object(Magento\Framework\Profiler\Driver\Standard\Stat))
#2 [internal function]: Magento\Framework\Profiler\Driver\Standard->display()
#3 {main}
  thrown in /Users/a12345/panel/magento/magento2.2/magento2/vendor/magento/framework/App/ObjectManager.php on line 35
`
Im on php
`12345s-MBP:magento2 a12345$ php -v
PHP 7.1.16 (cli) (built: Mar 31 2018 02:27:44) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.16, Copyright (c) 1999-2018, by Zend Technologies`

on mac with magento 2.2.3

**Comment by Triloworld** [comment]
Confirm. Solution @ityetti work right now fine and no problem. Pleas add information about Varnish that need to be clear manually and it works like charm 👍

**Comment by PascalBrouwers** [comment]
Tried to install. Had the same problem again.

**Comment by MurKit** [comment]
Looks like this fix does not work on 1.0.7
https://github.com/mirasvit/module-profiler/pull/44
Still having this problem
