### ISSUE TITLE
М2.2.2: extension crushes with conflict error

### ISSUE THREAD

**Issue by vtruhmanov** [mirasvit/module-profiler#30]
Error appears on installation on M2.2.2 with docker.

+ docker-compose exec --user www-data magento.ts.mirasvit.com /bin/sh -c '     cd /var/www/html;     composer require mirasvit/module-profiler:dev-master#4ec3c2590b45ab139a3e147de6b2276fcdbca78a || exit 1;     bin/magento module:enable --all;     bin/magento setup:upgrade;     if [ -f "/var/www/html/vendor/mirasvit/module-profiler/codeception/tests/acceptance.suite.yml.travis" ];      then      cp /var/www/html/vendor/mirasvit/module-profiler/codeception/tests/acceptance.suite.yml.travis /var/www/html/vendor/mirasvit/module-profiler/codeception/tests/acceptance.suite.yml;      cd /var/www/html/vendor/mirasvit/module-profiler/codeception/; composer install;
     fi;     '
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/yaml v4.0.2 requires php ^7.1.3 -> your PHP version (7.0.25) does not satisfy that requirement.
    - symfony/yaml v4.0.1 requires php ^7.1.3 -> your PHP version (7.0.25) does not satisfy that requirement.
    - symfony/yaml v4.0.0 requires php ^7.1.3 -> your PHP version (7.0.25) does not satisfy that requirement.
    - Conclusion: remove symfony/console v2.8.32
    - Conclusion: don't install symfony/console v2.8.32
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.32].
    - symfony/yaml v3.4.1 conflicts with symfony/console[v2.8.32].
    - symfony/yaml v3.4.2 conflicts with symfony/console[v2.8.32].
    - Installation request for symfony/console (locked at v2.8.32, required as ~2.3, !=2.7.0) -> satisfiable by symfony/console[v2.8.32].
    - Installation request for mirasvit/module-profiler dev-master#4ec3c2590b45ab139a3e147de6b2276fcdbca78a -> satisfiable by mirasvit/module-profiler[dev-master].
    - Conclusion: don't install symfony/dependency-injection v3.4.1|install symfony/yaml v3.4.0|install symfony/yaml v3.4.1|install symfony/yaml v3.4.2
    - Conclusion: remove symfony/dependency-injection v3.4.1|install symfony/yaml v3.4.0|install symfony/yaml v3.4.1|install symfony/yaml v3.4.2

**Comment by DmitryChukhnov** [comment]
Same error on 2.2.4.

If you try to install old version of yaml (3.3.16) get error: 
Problem 1
    - symfony/yaml v3.3.16 conflicts with symfony/dependency-injection[v3.4.9].
    - symfony/yaml v3.3.16 conflicts with symfony/dependency-injection[v3.4.9].
    - symfony/yaml v3.3.16 conflicts with symfony/dependency-injection[v3.4.9].
    - Installation request for symfony/yaml 3.3.16 -> satisfiable by symfony/yaml[v3.3.16].
    - Installation request for symfony/dependency-injection == 3.4.9.0 -> satisfiable by symfony/dependency-injection[v3.4.9].

**Comment by ioweb-gr** [comment]
Indeed I'm facing the same issue. There is no possible candidate for this to make it work in magento 2.2.6 or 2.2.7. I can't iinstall symfony/yaml either because of symfony/console restrictions or because of symfony/dependency-injection

**Comment by PascalBrouwers** [comment]
`composer require symfony/yaml:dev-issue-8145`
