### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by gediminaskv** [mirasvit/module-profiler#31]
I am using Magento 2.2. After `composer remove mirasvit/module-profiler` command get on frontend:

> Autoload error
> Cannot create standard driver output, class "Magento\Framework\Profiler\Driver\Standard\Output\Mirasvit\Profiler\Model\Driver\Output\Html" doesn't exist.

**Comment by adrok** [comment]
Try clear magento cache.

**Comment by gediminaskv** [comment]
Didn't help. Everything worked while Varnish daemon hasn't been restarted. Error is throwed after Varnish restart.

**Comment by iop** [comment]
I am using Magento 2.2. 
After composer remove mirasvit/module-profiler command get on frontend:
Autoload error
Cannot create standard driver output, class "Magento\Framework\Profiler\Driver\Standard\Output\Mirasvit\Profiler\Model\Driver\Output\Html" doesn't exist.

Varnish is not installed.

**Comment by adrok** [comment]
Check file app/etc/env.php, probably profiler wasn't disabled before removing.

**Comment by iop** [comment]
>> app/etc/env.php
profile=0 or remote it didn't fix issue: 
class "Magento\Framework\Profiler\Driver\Standard\Output\Mirasvit\Profiler\Model\Driver\Output\Html" doesn't exist.

**Comment by adrok** [comment]
Try find file which contain this line Mirasvit\Profiler\Model\Driver\Output\Html
