### ISSUE TITLE
#NDZ-932-78221- ошибки после установки профайлера

### ISSUE THREAD

**Issue by VikMirasvit** [mirasvit/module-profiler#35]
### Проблема

- [ ] Ошибки после установки профайлера:
I try to install Mirasvit Module Profiler and i cant to get work. After install and allow my IP, i have error 500 or empty/blank page or something like this:

There has been an error processing your request
Warning: file_get_contents(/opt/bitnami/apps/magento/htdocs/var/view_preprocessed/pub/static/vendor/mirasvit/module-profiler/src/Profiler/view/base/web/css/module.css): failed to open stream: No such file or directory in /opt/bitnami/apps/magento/htdocs/var/view_preprocessed/pub/static/vendor/mirasvit/module-profiler/src/Profiler/view/base/templates/root.phtml on line 1
Error log record number: 464823309575

I try to fix creating directory and copy the missed files but didn't succes. I get same error.

Magento 2.2.2-3 on google cloud server with varnish trought appache. I really need this extension for find some bootleneck on appache and varnish redirections when cache loads

### Доступы
#NDZ-932-78221

### Дополнительно

**Comment by shivampmc** [comment]
I have the same error, did you happen to fix it?
