### ISSUE TITLE
About Magento 2.3 Support

### ISSUE THREAD

**Issue by mozgbrasil** [mirasvit/module-profiler#48]
Hello good afternoon

About Magento 2.3 Support

As images we see that error is displayed when trying to install your module, can you help me

![captura de tela de 2019-02-06 16-39-40](https://user-images.githubusercontent.com/17202780/52365101-e081ab00-2a2d-11e9-8409-4be470820022.png)

Dependency resolution completed in 0.193 seconds
		Your requirements could not be resolved to an installable set of packages.

		  Problem 1
			- mirasvit/module-profiler 1.0.0 requires magento/framework 100.*.* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.1.0, 100.0.10, 100.0.11, 100.1.1, 100.0.12, 100.1.2, 100.1.3, 100.0.13, 100.1.4, 100.0.14, 100.1.5, 100.0.15, 100.1.6, 100.1.7, 100.0.16, 100.0.17, 100.1.8, 100.1.9, 100.0.18, 100.0.19, 100.1.10, 100.1.11, 100.0.20, 100.1.12, 100.1.13, 100.1.14, 100.1.15, 100.1.16].
			- mirasvit/module-profiler 1.0.1 requires magento/framework 100.*.* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.1.0, 100.0.10, 100.0.11, 100.1.1, 100.0.12, 100.1.2, 100.1.3, 100.0.13, 100.1.4, 100.0.14, 100.1.5, 100.0.15, 100.1.6, 100.1.7, 100.0.16, 100.0.17, 100.1.8, 100.1.9, 100.0.18, 100.0.19, 100.1.10, 100.1.11, 100.0.20, 100.1.12, 100.1.13, 100.1.14, 100.1.15, 100.1.16].
			- mirasvit/module-profiler 1.0.2 requires magento/framework 100.*.* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.1.0, 100.0.10, 100.0.11, 100.1.1, 100.0.12, 100.1.2, 100.1.3, 100.0.13, 100.1.4, 100.0.14, 100.1.5, 100.0.15, 100.1.6, 100.1.7, 100.0.16, 100.0.17, 100.1.8, 100.1.9, 100.0.18, 100.0.19, 100.1.10, 100.1.11, 100.0.20, 100.1.12, 100.1.13, 100.1.14, 100.1.15, 100.1.16].
			- mirasvit/module-profiler 1.0.3 requires magento/framework 100.*.* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.1.0, 100.0.10, 100.0.11, 100.1.1, 100.0.12, 100.1.2, 100.1.3, 100.0.13, 100.1.4, 100.0.14, 100.1.5, 100.0.15, 100.1.6, 100.1.7, 100.0.16, 100.0.17, 100.1.8, 100.1.9, 100.0.18, 100.0.19, 100.1.10, 100.1.11, 100.0.20, 100.1.12, 100.1.13, 100.1.14, 100.1.15, 100.1.16].
			- mirasvit/module-profiler 1.0.4 requires magento/framework 100.*.* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.1.0, 100.0.10, 100.0.11, 100.1.1, 100.0.12, 100.1.2, 100.1.3, 100.0.13, 100.1.4, 100.0.14, 100.1.5, 100.0.15, 100.1.6, 100.1.7, 100.0.16, 100.0.17, 100.1.8, 100.1.9, 100.0.18, 100.0.19, 100.1.10, 100.1.11, 100.0.20, 100.1.12, 100.1.13, 100.1.14, 100.1.15, 100.1.16].
			- mirasvit/module-profiler 1.0.5 requires magento/framework 100.*.* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.1.0, 100.0.10, 100.0.11, 100.1.1, 100.0.12, 100.1.2, 100.1.3, 100.0.13, 100.1.4, 100.0.14, 100.1.5, 100.0.15, 100.1.6, 100.1.7, 100.0.16, 100.0.17, 100.1.8, 100.1.9, 100.0.18, 100.0.19, 100.1.10, 100.1.11, 100.0.20, 100.1.12, 100.1.13, 100.1.14, 100.1.15, 100.1.16].
			- mirasvit/module-profiler 1.0.6 requires magento/framework 100.*|101.* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.1.0, 100.0.10, 100.0.11, 100.1.1, 100.0.12, 100.1.2, 100.1.3, 100.0.13, 100.1.4, 100.0.14, 100.1.5, 100.0.15, 100.1.6, 100.1.7, 100.0.16, 100.0.17, 100.1.8, 100.1.9, 100.0.18, 101.0.0, 100.0.19, 101.0.1, 100.1.10, 100.1.11, 101.0.2, 100.0.20, 100.1.12, 101.0.3, 100.1.13, 101.0.4, 101.0.5, 100.1.14, 100.1.15, 101.0.6, 100.1.16, 101.0.7].
			- magento/framework 101.0.7 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.1.16 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 101.0.6 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.1.15 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.1.14 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 101.0.5 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 101.0.4 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.1.13 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 101.0.3 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.1.12 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.20 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 101.0.2 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.1.11 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.1.10 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 101.0.1 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.19 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 101.0.0 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.18 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.1.9 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.1.8 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.17 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.16 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.1.7 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.1.6 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.15 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.1.5 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.14 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.1.4 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.13 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.1.3 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.1.2 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.12 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.1.1 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.11 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.10 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.1.0 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.9 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.8 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.7 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.6 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.5 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.4 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.3 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- magento/framework 100.0.2 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
			- Installation request for mirasvit/module-profiler ^1.0 -> satisfiable by mirasvit/module-profiler[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6].

**Comment by WebKenth** [comment]
@mozgbrasil  It would help if you read the error message thrown in your face ;-) 

You are using an old outdated Php Version

![image](https://user-images.githubusercontent.com/13419123/174042707-8e9268aa-97da-41ae-b9f9-c5cd2cc133de.png)
