### ISSUE TITLE
Profiler is causing problems with di:compile

### ISSUE THREAD

**Issue by paales** [mirasvit/module-profiler#7]
I had the following conversation on a Magento chat.

> Paul [3:30 PM]
> I'm having trouble running di-compile, the .ser files generated in var/di causing errors
>  Running into the following error: http://cloud.h-o.nl/hl2k
> 
> Someone else [3:34 PM]
> Upgraded to 2.1.2 in composer, worked perfectly, also with di-compile
> 
> Paul [3:35 PM]
> Hmm
> The exception is super unclear
> Even if I suppress the statement it seems to be working just fine..
> @mhauri Have you also tested with mode set to production and having ran setup:di:compile
> This is causing the problems.. http://cloud.h-o.nl/hlKw
> 
> Someone else [3:43 PM]
> Did you tried to remove all files in var/di and run again
> 
> Paul [3:43 PM]
> Yeah, multiple times
> I had installed a third party profiler, deleting now.
> It seems that when a new profiler driver is added it also enabled the profiler, although it isn't actually requested to be enabled.

It seems to be enabled here: `\Magento\Framework\Profiler::add()`. So i guess it should do some checks if it should actually add the driver.

**Comment by adrok** [comment]
Please clarify magento version.

**Comment by paales** [comment]
Magento 2.1.2, running in production mode after compilation :)
